export const paths = {
  launch: '/',
  home: '/home',
  bible: '/bible',
  hymnal: '/hymnal',
  news: '/news',
  forum: '/forum',
  ministries: '/ministries',
  donation: '/donation',
  media: '/media',
  church: '/church',
  resources: '/resources',
  discipleship: '/discipleship',
  wallet: '/wallet',
  walletTransactions: (walletNumber: string) => `/wallet/${encodeURIComponent(walletNumber)}/transactions`,
  walletTransactionsRoute: '/wallet/:walletNumber/transactions',
  walletTransactionDetails: (walletNumber: string, transactionId: string) =>
    `/wallet/${encodeURIComponent(walletNumber)}/transactions/${encodeURIComponent(transactionId)}`,
  walletTransactionDetailsRoute: '/wallet/:walletNumber/transactions/:transactionId',
  walletFundingCallback: '/wallet/funding/callback',
  profile: '/profile',
  settings: '/settings',
  devotional: '/devotional',
  sundaySchool: '/sunday-school',
  login: '/auth/login',
  googleRedirect: '/google-redirect',
  emailVerify: '/auth/email-verify',
  register: '/auth/register',
  registerVerification: '/auth/register/verify-email',
  forgotPassword: '/auth/forgot-password',
  verifyOtp: '/auth/verify-otp',
  resetPassword: '/auth/reset-password',
} as const;
