export const paths = {
  launch: '/',
  home: '/home',
  bible: '/bible',
  hymnal: '/hymnal',
  events: '/events',
  news: '/news',
  forum: '/forum',
  forumDetails: (forumId: string) => `/forum/${encodeURIComponent(forumId)}`,
  forumDetailsRoute: '/forum/:forumId',
  ministries: '/ministries',
  donation: '/donation',
  media: '/media',
  church: '/church',
  churchBrowse: '/church/browse',
  churchDocuments: '/church/documents',
  churchEvents: '/church/events',
  churchRegistrationReview: '/church-registration/review',
  churchRegistrationReviewWithToken: (token: string) =>
    `/church-registration/review/${encodeURIComponent(token)}`,
  churchRegistrationReviewTokenRoute: '/church-registration/review/:token',
  churchLeadership: (type: string) => `/church/leadership/${encodeURIComponent(type)}`,
  churchLeadershipRoute: '/church/leadership/:type',
  family: '/family',
  familyInvite: '/family/invite',
  familyMembers: '/family/members',
  familyRequests: '/family/requests',
  resources: '/resources',
  discipleship: '/discipleship',
  wallet: '/wallet',
  walletTransactions: (walletNumber: string) =>
    `/wallet/${encodeURIComponent(walletNumber)}/transactions`,
  walletTransactionsRoute: '/wallet/:walletNumber/transactions',
  walletTransactionDetails: (walletNumber: string, transactionId: string) =>
    `/wallet/${encodeURIComponent(walletNumber)}/transactions/${encodeURIComponent(transactionId)}`,
  walletTransactionDetailsRoute: '/wallet/:walletNumber/transactions/:transactionId',
  walletFundingCallback: '/wallet/funding/callback',
  givingCallback: '/giving/callback',
  profile: '/profile',
  settings: '/settings',
  devotional: '/devotional',
  sundaySchool: '/sunday-school',
  login: '/auth/login',
  googleRedirect: '/google-redirect',
  emailVerify: '/auth/email-verify',
  register: '/auth/register',
  registerVerification: '/auth/register/verify-email',
  forgotPassword: '/auth/forgot-password',
  verifyOtp: '/auth/verify-otp',
  resetPassword: '/auth/reset-password',
} as const;
